package com.example.zammad.core

/**
 * In-app localization: two complete tables (en, ru) — the same keys as the
 * iOS app. `L10n.code` is set from preferences at startup and on change.
 */
object L10n {
    var code: String = "en"

    fun t(key: String): String {
        if (code == "ru") {
            Strings.ru[key]?.let { return it }
        }
        return Strings.en[key] ?: key
    }

    /** Maps an API error to its localized message key. */
    fun messageKeyFor(kind: String): String = "error.$kind"

    private object Strings {
        val en: Map<String, String> = mapOf(
            "common.loading" to "Loading…",
            "common.cancel" to "Cancel",
            "common.ok" to "OK",
            "common.retry" to "Try again",
            "common.close" to "Close",
            "common.save" to "Save",
            "common.done" to "Done",
            "common.unknown" to "Unknown",

            "connect.title" to "Connect to Zammad",
            "connect.subtitle" to "Enter your helpdesk address and sign in",
            "connect.server" to "Server address",
            "connect.server.placeholder" to "https://help.example.com",
            "connect.auth" to "Authorization",
            "connect.auth.token" to "API token",
            "connect.auth.password" to "Login and password",
            "connect.token" to "Personal access token",
            "connect.token.hint" to "Create it in Zammad: Profile → Personal access tokens.",
            "connect.username" to "Login",
            "connect.password" to "Password",
            "connect.password.hint" to "The password is exchanged for an API token when the server allows it, otherwise HTTP Basic is used.",
            "connect.submit" to "Connect",
            "connect.connecting" to "Connecting…",
            "connect.error.url" to "Enter the server address, e.g. https://help.example.com",
            "connect.error.token" to "Enter your API token",
            "connect.error.credentials" to "Enter your login and password",

            "tab.tickets" to "Tickets",
            "tab.new" to "New",
            "tab.settings" to "Settings",

            "tickets.title" to "Tickets",
            "tickets.search" to "Search tickets",
            "tickets.filter.all" to "All",
            "tickets.filter.open" to "Open",
            "tickets.filter.mine" to "Mine",
            "tickets.filter.closed" to "Closed",
            "tickets.empty" to "No tickets",
            "tickets.empty.hint" to "Pull the list to refresh or change the filter.",
            "tickets.empty.search" to "Nothing found",
            "tickets.empty.search.hint" to "Try another search request.",
            "tickets.loadMore" to "Load more",
            "tickets.refresh" to "Refresh",

            "ticket.state" to "State",
            "ticket.priority" to "Priority",
            "ticket.group" to "Group",
            "ticket.customer" to "Customer",
            "ticket.owner" to "Owner",
            "ticket.organization" to "Organization",
            "ticket.created" to "Created",
            "ticket.updated" to "Updated",
            "ticket.messages" to "Messages",
            "ticket.noMessages" to "No messages yet.",
            "ticket.actions" to "Ticket actions",
            "ticket.changeState" to "Change state",
            "ticket.changePriority" to "Change priority",
            "ticket.changeGroup" to "Change group",
            "ticket.assign" to "Assign to",
            "ticket.assign.me" to "Assign to me",
            "ticket.assign.unassigned" to "Unassigned",
            "ticket.assign.search" to "Search agents",
            "ticket.assign.empty" to "No agents found",

            "reply.public" to "Public reply",
            "reply.internal" to "Internal note",
            "reply.placeholder" to "Write a message…",
            "reply.send" to "Send",
            "reply.sending" to "Sending…",
            "reply.internalHint" to "Visible only to agents",

            "article.internal" to "Internal",

            "attachment.download" to "Downloading file:",

            "new.title" to "New ticket",
            "new.subject" to "Subject",
            "new.subject.placeholder" to "How can we help?",
            "new.group" to "Group",
            "new.customer" to "Customer email",
            "new.customer.placeholder" to "customer@example.com",
            "new.priority" to "Priority",
            "new.state" to "State",
            "new.message" to "First message",
            "new.message.placeholder" to "Describe the request…",
            "new.submit" to "Create ticket",
            "new.creating" to "Creating…",
            "new.error.title" to "Enter the subject",
            "new.error.group" to "Choose a group",
            "new.error.message" to "Enter the message text",

            "settings.title" to "Settings",
            "settings.language" to "Language",
            "settings.language.system" to "System",
            "settings.appearance" to "Appearance",
            "settings.appearance.system" to "System",
            "settings.appearance.light" to "Light",
            "settings.appearance.dark" to "Dark",
            "settings.connection" to "Connection",
            "settings.server" to "Server",
            "settings.account" to "Account",
            "settings.auth" to "Authorization",
            "settings.disconnect" to "Disconnect",
            "settings.disconnect.question" to "Disconnect from the server? The saved credentials will be removed.",
            "settings.about" to "About",
            "settings.version" to "Version",
            "settings.api" to "API documentation",

            "error.network" to "No connection to the server. Check the address and your network.",
            "error.unauthorized" to "Authorization failed. Check your token, login or password.",
            "error.forbidden" to "This account has no access rights.",
            "error.notFound" to "Not found on the server.",
            "error.server" to "The server returned an error.",
            "error.request" to "Request failed.",
            "error.decode" to "Could not read the server response.",
            "error.invalidURL" to "Invalid server address.",
            "error.unknown" to "Something went wrong."
        )

        val ru: Map<String, String> = mapOf(
            "common.loading" to "Загрузка…",
            "common.cancel" to "Отмена",
            "common.ok" to "ОК",
            "common.retry" to "Повторить",
            "common.close" to "Закрыть",
            "common.save" to "Сохранить",
            "common.done" to "Готово",
            "common.unknown" to "Неизвестно",

            "connect.title" to "Подключение к Zammad",
            "connect.subtitle" to "Укажите адрес хелпдеска и войдите в систему",
            "connect.server" to "Адрес сервера",
            "connect.server.placeholder" to "https://help.example.com",
            "connect.auth" to "Авторизация",
            "connect.auth.token" to "API-токен",
            "connect.auth.password" to "Логин и пароль",
            "connect.token" to "Персональный токен",
            "connect.token.hint" to "Создаётся в Zammad: Профиль → Персональные токены.",
            "connect.username" to "Логин",
            "connect.password" to "Пароль",
            "connect.password.hint" to "Пароль обменивается на API-токен, если сервер это разрешает; иначе используется HTTP Basic.",
            "connect.submit" to "Подключиться",
            "connect.connecting" to "Подключение…",
            "connect.error.url" to "Укажите адрес сервера, например https://help.example.com",
            "connect.error.token" to "Укажите API-токен",
            "connect.error.credentials" to "Укажите логин и пароль",

            "tab.tickets" to "Тикеты",
            "tab.new" to "Создать",
            "tab.settings" to "Настройки",

            "tickets.title" to "Тикеты",
            "tickets.search" to "Поиск тикетов",
            "tickets.filter.all" to "Все",
            "tickets.filter.open" to "Открытые",
            "tickets.filter.mine" to "Мои",
            "tickets.filter.closed" to "Закрытые",
            "tickets.empty" to "Нет тикетов",
            "tickets.empty.hint" to "Потяните список для обновления или смените фильтр.",
            "tickets.empty.search" to "Ничего не найдено",
            "tickets.empty.search.hint" to "Попробуйте другой запрос.",
            "tickets.loadMore" to "Показать ещё",
            "tickets.refresh" to "Обновить",

            "ticket.state" to "Статус",
            "ticket.priority" to "Приоритет",
            "ticket.group" to "Группа",
            "ticket.customer" to "Клиент",
            "ticket.owner" to "Ответственный",
            "ticket.organization" to "Организация",
            "ticket.created" to "Создан",
            "ticket.updated" to "Обновлён",
            "ticket.messages" to "Сообщения",
            "ticket.noMessages" to "Сообщений пока нет.",
            "ticket.actions" to "Действия с тикетом",
            "ticket.changeState" to "Изменить статус",
            "ticket.changePriority" to "Изменить приоритет",
            "ticket.changeGroup" to "Изменить группу",
            "ticket.assign" to "Назначить",
            "ticket.assign.me" to "Назначить на меня",
            "ticket.assign.unassigned" to "Не назначен",
            "ticket.assign.search" to "Поиск сотрудников",
            "ticket.assign.empty" to "Сотрудники не найдены",

            "reply.public" to "Публичный ответ",
            "reply.internal" to "Внутренняя заметка",
            "reply.placeholder" to "Напишите сообщение…",
            "reply.send" to "Отправить",
            "reply.sending" to "Отправка…",
            "reply.internalHint" to "Видно только сотрудникам",

            "article.internal" to "Внутр.",

            "attachment.download" to "Скачивание файла:",

            "new.title" to "Новый тикет",
            "new.subject" to "Тема",
            "new.subject.placeholder" to "Чем помочь?",
            "new.group" to "Группа",
            "new.customer" to "Email клиента",
            "new.customer.placeholder" to "customer@example.com",
            "new.priority" to "Приоритет",
            "new.state" to "Статус",
            "new.message" to "Первое сообщение",
            "new.message.placeholder" to "Опишите запрос…",
            "new.submit" to "Создать тикет",
            "new.creating" to "Создание…",
            "new.error.title" to "Укажите тему",
            "new.error.group" to "Выберите группу",
            "new.error.message" to "Укажите текст сообщения",

            "settings.title" to "Настройки",
            "settings.language" to "Язык",
            "settings.language.system" to "Системный",
            "settings.appearance" to "Оформление",
            "settings.appearance.system" to "Системное",
            "settings.appearance.light" to "Светлое",
            "settings.appearance.dark" to "Тёмное",
            "settings.connection" to "Подключение",
            "settings.server" to "Сервер",
            "settings.account" to "Аккаунт",
            "settings.auth" to "Авторизация",
            "settings.disconnect" to "Отключиться",
            "settings.disconnect.question" to "Отключиться от сервера? Сохранённые данные входа будут удалены.",
            "settings.about" to "О приложении",
            "settings.version" to "Версия",
            "settings.api" to "Документация API",

            "error.network" to "Нет связи с сервером. Проверьте адрес и сеть.",
            "error.unauthorized" to "Ошибка авторизации. Проверьте токен, логин или пароль.",
            "error.forbidden" to "У аккаунта нет прав доступа.",
            "error.notFound" to "Не найдено на сервере.",
            "error.server" to "Сервер вернул ошибку.",
            "error.request" to "Запрос не выполнен.",
            "error.decode" to "Не удалось прочитать ответ сервера.",
            "error.invalidURL" to "Некорректный адрес сервера.",
            "error.unknown" to "Что-то пошло не так."
        )
    }
}
